name: "Verify Translation"

on:
  push:
    paths:
      - '**/strings.xml'
  pull_request:
    paths:
      - '**/strings.xml'

jobs:
  run-kts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kotlin
        run: sudo apt-get update && sudo apt-get install -y kotlin

      - name: Run Kotlin script
        run: kotlin .github/workflows/verifyTranslations.kts
